name: slimy_card
description: It provides a beautiful slime-like animation of a Card that separates into two.
version: 1.0.4
homepage: https://github.com/AkashDivya/SlimyCard-Animated-Flutter-Project

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flare_flutter: 3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
   - assets/flare/